version: '2'
services:
    moveapp-app:
        image: moveapp
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:postgresql://moveapp-postgresql:5432/MoveApp
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    moveapp-postgresql:
        extends:
            file: postgresql.yml
            service: moveapp-postgresql
